kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: logging-psp
  namespace: logging
rules:
  - apiGroups: ["extensions"]
    resources: ["podsecuritypolicies"]
    resourceNames: ["logging-privileged"]
    verbs: ["use"]
