apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: es-master
  namespace: appteam
  labels:
    component: elasticsearch
    role: master
spec:
  replicas: 3
  template:
    metadata:
      labels:
        component: elasticsearch
        role: master
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es-master
        securityContext:
          privileged: false
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        image: quay.io/pires/docker-elasticsearch-kubernetes:5.5.2
        imagePullPolicy: Always
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: es-logging-appteam
              key: cluster.name
        - name: NUMBER_OF_MASTERS
          valueFrom:
            configMapKeyRef:
              name: es-logging-appteam
              key: cluster.master_count
        - name: NODE_MASTER
          value: "true"
        - name: NODE_INGEST
          valueFrom:
            configMapKeyRef:
              name: es-logging-appteam
              key: master_nodes.ingest
        - name: NODE_DATA
          valueFrom:
            configMapKeyRef:
              name: es-logging-appteam
              key: master_nodes.store_data
        - name: HTTP_ENABLE
          valueFrom:
            configMapKeyRef:
              name: es-logging-appteam
              key: master_nodes.http_enable
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: es-logging-appteam
              key: master_nodes.java_opts
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
      volumes:
          - emptyDir:
              medium: ""
            name: "storage"
