apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kibana-system
  namespace: tectonic-system
  labels:
    component: kibana-system
spec:
  replicas: 1
  selector:
    matchLabels:
     component: kibana-system
  template:
    metadata:
      labels:
        component: kibana-system
    spec:
      containers:
      - name: kibana
        image: cfontes/kibana-xpack-less:5.5.0
        imagePullPolicy: Always
        env:
        - name: ELASTICSEARCH_URL
          value: https://elasticsearch.logging.svc.cluster.local:9200
        - name: ELASTICSEARCH_USERNAME
          value: kibana
        - name: ELASTICSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: es-pwd-kibana-secret
              key: password
        - name: ELASTICSEARCH_SSL_VERIFICATIONMODE
          value: none
        - name: SERVER_BASEPATH
          value: /logging-system
        - name: SERVER_NAME
          value: kibana-system
        - name: SERVER_HOST
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: XPACK_SECURITY_ENABLED
          value: 'false'
        - name: XPACK_GRAPH_ENABLED
          value: 'false'
        - name: XPACK_ML_ENABLED
          value: 'false'
        - name: XPACK_REPORTING_ENABLED
          value: 'false'
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        ports:
        - containerPort: 5601
          name: kibana
          protocol: TCP
