apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: es-data
  namespace: logging
  labels:
    component: elasticsearch
    role: data
spec:
  serviceName: elasticsearch-data
  replicas: 3
  template:
    metadata:
      labels:
        component: elasticsearch
        role: data
    spec:
      initContainers:
      - name: init-sysctl
        image: busybox
        imagePullPolicy: IfNotPresent
        command: ["sysctl", "-w", "vm.max_map_count=262144"]
        securityContext:
          privileged: true
      containers:
      - name: es-data
        securityContext:
          privileged: true
          capabilities:
            add:
              - IPC_LOCK
        image: quay.io/lander2k2/docker-elasticsearch-kubernetes:5.5.0
        command: ["/run.sh"]
        imagePullPolicy: Always
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: NODE_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: CLUSTER_NAME
          valueFrom:
            configMapKeyRef:
              name: es-logging
              key: cluster.name
        - name: SERVICE_DNS
          valueFrom:
            configMapKeyRef:
              name: es-logging
              key: data_nodes.service_dns
        - name: NODE_MASTER
          value: "false"
        - name: NODE_INGEST
          valueFrom:
            configMapKeyRef:
              name: es-logging
              key: data_nodes.ingest
        - name: NODE_DATA
          valueFrom:
            configMapKeyRef:
              name: es-logging
              key: data_nodes.store_data
        - name: HTTP_ENABLE
          valueFrom:
            configMapKeyRef:
              name: es-logging
              key: data_nodes.http_enable
        - name: NODE_MASTER
          value: "false"
        - name: ES_JAVA_OPTS
          valueFrom:
            configMapKeyRef:
              name: es-logging
              key: data_nodes.java_opts
        - name: ADMIN_PWD
          valueFrom:
            secretKeyRef:
              name: es-pwd-admin-secret
              key: password
        - name: LOGSTASH_PWD
          valueFrom:
            secretKeyRef:
              name: es-pwd-fluentd-secret
              key: password
        - name: KIBANA_PWD
          valueFrom:
            secretKeyRef:
              name: es-pwd-kibana-secret
              key: password
        ports:
        - containerPort: 9300
          name: transport
          protocol: TCP
        volumeMounts:
        - name: storage
          mountPath: /data
        - name: sg-config
          mountPath: /elasticsearch/config/searchguard
        - name: tls-ca-chain
          mountPath: /elasticsearch/config/tls/ca_chain
          readOnly: false
        - name: tls-admin
          mountPath: /elasticsearch/config/tls/admin
          readOnly: false
      volumes:
      - name: sg-config
        configMap:
          name: searchguard-config
      - name: tls-ca-chain
        secret:
          secretName: es-tls-ca-chain-secret
      - name: tls-admin
        secret:
          secretName: es-tls-admin-secret
  volumeClaimTemplates:
  - metadata:
      name: storage
      annotations:
        volume.beta.kubernetes.io/storage-class: standard
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 12Gi
