# Allow kube-controller-manager to have permissive PSP access for stateful sets in appteam namespace
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: logging-psp
  namespace: appteam
subjects:
- kind: ServiceAccount
  name: replicaset-controller
  namespace: kube-system
- kind: ServiceAccount
  name: daemon-set-controller
  namespace: kube-system
- kind: ServiceAccount
  name: statefulset-controller
  namespace: kube-system
roleRef:
  kind: Role
  name: logging-psp
  apiGroup: rbac.authorization.k8s.io

