kind: DaemonSet
apiVersion: extensions/v1beta1
metadata:
  name: fluentd
  labels:
    app: fluentd
    version: v1
    kubernetes.io/cluster-service: "true"
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: fluentd
        version: v1
        kubernetes.io/cluster-service: "true"
    spec:
      tolerations:
      - key: "node-role.kubernetes.io/master"
        operator: "Exists"
        effect: "NoSchedule"
      serviceAccount: fluentd
      serviceAccountName: fluentd
      imagePullSecrets:
        - name: registry-creds
      containers:
      - command:
        - fluentd
        - -c
        - /fluentd/etc/fluentd.conf
        - -p
        - /fluentd/plugins
        env:
        - name: FLUENTD_CONFIG
          value: fluentd-standalone.conf
      - name: fluentd
        image: quay.io/namespace/containername:tag
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 300m
            memory: 4Gi
        securityContext:
          privileged: true
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-config
          mountPath: /fluentd/etc
      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
       - configMap:
          defaultMode: 420
          name: fluentd-config