kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: read-pods
subjects:
- kind: ServiceAccount
  name: logging
  namespace: logging
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
